name: github pages

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          docker run --rm --volume="${{ github.workspace }}:/home/rstudio" \
          carpentries/lesson-docker:latest /bin/bash -c \
          "gem install bundler && \ 
          bundle config --local set path .vendor/bundle && \
          bundle install && \
          bundle exec jekyll build --trace"
